### ISSUE TITLE
question: accuracy/numerical stability test?

### ISSUE THREAD

**Issue by kruus** [andravin/wincnn#1]
Not really an issue -- just hoping you'll comment...

Elsewhere, you have made comments about numerical stability.  How is this tested? Is there public code to test this?
- I assumed that coefficient range in at,g,bt (as opposed to nice power of 2 multipliers) was a factor.
  - My hypothesis was that perhaps the 1/32 to 32 range (3 orders of magnitude) **might** be a bit large for accurate summations (even though the multiplies themselves are exact)
- This **presumes** that it is the summations are a big source of instability (perhaps wrong).
- I looked at a number of criteria for the ranges of the non-zero coeffs in at,g,bt.
- On that basis, some searching using wincnn suggests for F(6,3) that cookToomFilter(0, +/-5/6, +/-1, +/-7/6) is somewhat nice.
  - (Some others I found are about as nice, and also have some power-of-two-ness in them)

Eventually, I'd like some way to estimate numerical accuracy, esp. for inputs typical in neural nets.
Can you could point me to some easy path?  Is comparing float to double calculation the easiest approach?
- Or is "numerical stability" kind of ill-defined without picking an actual implementation?
  - E.g. having +/- coefficients of same value, the particular order for the summation counts and in principle one would like to add small things first, followed by summing large contributions.  Not sure whether vectorized CPU versions in NNPACK have much control over this. Speed is probably more of an issue than controlling the summation order.

Thanks for putting wincnn 'out there'.

Erik.

**----------- Detail:**
- (m,i,j,k) are my search-space parameters for 0,+/-(m+i)/m,+/-(m+j)/m,+/-(m+k)/m
- sum, clust1, range1 some artificial "goodness" measures
  - I also looked at less symmetrical search spaces, but did not find any that caught my eye
- summary line has Matrix[lo,hi]>=min(abs([all non-zero values]))

m=6  i=-1 j=0  k=1   sum|lims|=21.59316   clust1=14.67674   range1=14.30971  : |at[ -2.161394, 2.161394  ]|>=0.4018776    |g[ -4.531469, 4.531469  ]|>=1            |bt[ -3.055556, 3.055556  ]|>=0.6944444
###### at =

[[ 1.          1.          1.          1.          1.          1.          1.          0.        ]
 [ 0.          0.83333331 -0.83333331  1.         -1.          1.16666663 -1.16666663  0.        ]
 [ 0.          0.69444442  0.69444442  1.          1.          1.36111116  1.36111116  0.        ]
 [ 0.          0.5787037  -0.5787037   1.         -1.          1.58796299 -1.58796299  0.        ]
 [ 0.          0.48225307  0.48225307  1.          1.          1.85262346  1.85262346  0.        ]
 [ 0.          0.40187758 -0.40187758  1.         -1.          2.16139412 -2.16139412  1.        ]]
        g  =
[[ 1.0579592   0.          0.        ]
 [ 3.53454542  2.9454546   2.4545455 ]
 [ 3.53454542 -2.9454546   2.4545455 ]
 [-4.53146839 -4.53146839 -4.53146839]
 [-4.53146839  4.53146839 -4.53146839]
 [ 1.52590263  1.78021979  2.07692313]
 [ 1.52590263 -1.78021979  2.07692313]
 [ 0.          0.          1.        ]]
        bt =
[[ 0.94521606  0.         -3.00077152  0.          3.05555558  0.         -1.          0.        ]
 [ 0.          1.13425922  1.36111116 -1.9675926  -2.36111116  0.83333331  1.          0.        ]
 [ 0.         -1.13425922  1.36111116  1.9675926  -2.36111116 -0.83333331  1.          0.        ]
 [ 0.          0.94521606  0.94521606 -2.05555558 -2.05555558  1.          1.          0.        ]
 [ 0.         -0.94521606  0.94521606  2.05555558 -2.05555558 -1.          1.          0.        ]
 [ 0.          0.81018519  0.69444442 -1.97685182 -1.69444442  1.16666663  1.          0.        ]
 [ 0.         -0.81018519  0.69444442  1.97685182 -1.69444442 -1.16666663  1.          0.        ]
 [ 0.         -0.94521606  0.          3.00077152  0.         -3.05555558  0.          1.        ]]
FFFFFFF at = Matrix([
[1,         1,          1, 1,  1,          1,           1, 0],
[0,       5/6,       -5/6, 1, -1,        7/6,        -7/6, 0],
[0,     25/36,      25/36, 1,  1,      49/36,       49/36, 0],
[0,   125/216,   -125/216, 1, -1,    343/216,    -343/216, 0],
[0,  625/1296,   625/1296, 1,  1,  2401/1296,   2401/1296, 0],
[0, 3125/7776, -3125/7776, 1, -1, 16807/7776, -16807/7776, 1]])
        g  = Matrix([
[1296/1225,        0,        0],
[  972/275,   162/55,    27/11],
[  972/275,  -162/55,    27/11],
[ -648/143, -648/143, -648/143],
[ -648/143,  648/143, -648/143],
[  972/637,   162/91,    27/13],
[  972/637,  -162/91,    27/13],
[        0,        0,        1]])
        bt = Matrix([
[1225/1296,          0, -3889/1296,         0,  55/18,      0, -1, 0],
[        0,    245/216,      49/36,  -425/216, -85/36,    5/6,  1, 0],
[        0,   -245/216,      49/36,   425/216, -85/36,   -5/6,  1, 0],
[        0,  1225/1296,  1225/1296,    -37/18, -37/18,      1,  1, 0],
[        0, -1225/1296,  1225/1296,     37/18, -37/18,     -1,  1, 0],
[        0,    175/216,      25/36,  -427/216, -61/36,    7/6,  1, 0],
[        0,   -175/216,      25/36,   427/216, -61/36,   -7/6,  1, 0],
[        0, -1225/1296,          0, 3889/1296,      0, -55/18,  0, 1]])

**Comment by andravin** [comment]
Hi @kruus , these are important questions. :-)

In the _Fast Algorithms for Convnets_ paper I estimated numeric accuracy of the kernels by comparing the fp32 or fp16 implementation with fp64 direct convolution, measuring the maximum absolute value error over a set of random weights and activations in the range [-1,1].

The  inverse transform weights can be scaled if you like by multiplying any of the columns of AT by a scalar, and multiplying the corresponding row of G or BT by the reciprocal of that scalar. You could use this to decrease the dynamic range of AT for the F(6,3) algorithm (ie multiply the columns that contain 1/32 by the number 32). But the accuracy of the forward transforms G and BT are more important.

**Comment by kruus** [comment]
Thanks for the simple and clear reply.  The accuracy estimation procedure seems very reasonable. In fact, I had also wondered about the details behind the mysterious rescale_coefficients parameter in the NNPACK code and some of your earlier rescaling comments :)
