### ISSUE TITLE
fast multiplication of complex numbers (from the paper: Fast Algorithms for Convolutional Neural Networks)

### ISSUE THREAD

**Issue by adam-dziedzic** [andravin/wincnn#14]
Hi Andrew,

I believe that there is a small mistake in your paper regarding the fast multiplication of complex numbers, it should be: (x0 + ix1)(y0 + iy1) = ua*vc - ub*vb + i(uc*va + ua*vc)  (the order of real and imaginary parts should be swapped).

**Comment by andravin** [comment]
Thanks, another reader also noticed this. Trying to decide whether to just
make an errata page here or update the paper.

**Comment by adam-dziedzic** [comment]
IMHO, I suppose most people download the paper from https://arxiv.org/abs/1509.09308 so probably updating the source-of-the-truth would be better.

**Comment by andravin** [comment]
Yes that makes sense. There is another typo in the definition of "alpha" in the arithmetic complexity formula, caught by another careful reader. So I will correct both and update the paper on arxiv.org. Thanks

**Comment by adam-dziedzic** [comment]
You're welcome.
