### ISSUE TITLE
Number of tiles per channel (to compute convnet layers with F(2 x 2, 3 x 3))

### ISSUE THREAD

**Issue by adam-dziedzic** [andravin/wincnn#17]
Shouldn't the number of tiles per channel be: `P = N * [(W - (m+r-1)) / (r-1) + 1]*[(H - (m+r-1)) / (r-1) + 1]`, or am I missing something? Current formula is: `P = N*ceil(H/m)*ceil(W/m)` (this is top row on page 3 of the paper: [https://arxiv.org/abs/1509.09308](https://arxiv.org/abs/1509.09308)). 

To give some more details, my formula is similar to computing size of the output for convolution with stride for a filter. Here, our stride for tiles is s=2 (filter of size r=3, thus: stride s = r - 1). The tile size t = m+r-1. Thus, the number of tiles is: `P = N * ((W-t)/s + 1) * ((H-t)/s + 1)`. 

If consider an example with input map 6x6 for F(2 x 2, 3 x 3), where r=3, m=2, then the number of tiles should be 4. The tile size is t = m + r - 1 = 4. Stride s = r-1=2. W=H=6. Number of tiles `P = 1 * ((6 - 4)/2 + 1) * ((6-4)/2 + 1) = 4`. However, the formula in the paper gives us: `P = ceil(H/m) * ceil(W/m) = 6/2 * 6/2 = 3 * 3 = 9`. 

Is my understanding correct or I missed something about tiles? I implemented the algorithm: [https://github.com/adam-dziedzic/winograd](https://github.com/adam-dziedzic/winograd)

**Comment by andravin** [comment]
F(mxn,rxs) computes mxn outputs by correlating an rxs filter with
(m+r-1,n+s-1) inputs.

Since the algorithm computes mxn outputs at a time, divide the output
dimensions by that tile size.

Hope that helps.

**Comment by adam-dziedzic** [comment]
Thank you for your response @andravin I suppose that when you were giving the formula for the number of tiles: `P = ceil(H/m) * ceil(W/m)` (at the top of the 3rd page of your paper), you meant that HxW is the dimension of the output of the convolution, and not the dimension of the input (images). If so, then the formula is correct and for my example with input map of size 6x6, filter 3x3, the output size is 4x4. Then the number of tiles is 4/2 * 4/2 = 4. I was a bit confused because you also mentioned at the beginning of section 3 (in your paper) that the input is N batches with C channels, and images of size HxW.

**Comment by andravin** [comment]
Yes, you got it. In the paper, I assume padding around the input image to make the output size equal the input size. This is common (though not universal) practice in convolutional neural networks, and is sometimes called "SAME" padding.

**Comment by adam-dziedzic** [comment]
Thank you @andravin for confirming this and for your further clarification. 

Let me spill my implementation thoughts into this answer. The HxW size is the size of the input (without padding) and also the size of the output because we use the "same" mode for convolution (and pad the input to avoid any boundary effects). An example: we have an input of size 4x4 and want the output of size 4x4, then we use zero padding on each side of the input, which gives us a 6x6 input map. The input map is divided into 4 tiles (4x4 each) and we use the standard F(2x2,3x3) transformations that give us 2x2 output each, next they are stitch together to obtain the final output of size 4x4.

**Comment by andravin** [comment]
Yes, that's it. 

Also, you can think of the data transform as downsampling with a (spatially separable) depthwise convolution that expands the number of channels into the number of winograd components.

Likewise, you can think of the inverse transform as upsampling with a (spatially separable) grouped convolution that compresses the number of winograd components into the number of channels.

This idea was generalized in one of my favorite papers, "StrassenNets: Deep Learning with a Multiplication Budget", found here: https://arxiv.org/pdf/1712.03942.pdf

Source code for that project is here: https://github.com/mitscha/strassennets
