### ISSUE TITLE
How to calculate the transform matrixes for F(MxN, 5x3) formal.

### ISSUE THREAD

**Issue by lujnan** [andravin/wincnn#18]

**Comment by andravin** [comment]
You can experiment with different polynomial roots, but here is one choice:

`wincnn.showCookToomFilter((0,1,-1,2,-2,Rational(1,2)), 5, 3)`

**Comment by lujnan** [comment]
> You can experiment with different polynomial roots, but here is one choice:
> 
> `wincnn.showCookToomFilter((0,1,-1,2,-2,Rational(1,2)), 5, 3)`

Andravin, I'm so sorry, I would say that how to calc the transform matrixes for F(MxN, 5x3) formal.

**Comment by andravin** [comment]
Ah, I misunderstood the question.

The technique is to nest F(M,5) with F(N,3). In other words, apply F(M,5) vertically to the activations, then apply F(N,3) horizontally to each of the vertical components.

So you need algorithms for F(M,5) and F(N,3).

The choice mostly comes down to choices of M and N. For float32 inference, the largest values you might be able to use without suffering numeric accuracy problems might be M=4 and N=6. For training, M=2 and N=4.

Another possibility is to use FFT for F(M,5) and Winograd for F(N,3). Then you could make M large without worrying about numeric accuracy. Still another possibility is to use a non-minimal Winograd convolution algorithm for F(M,5). These use polynomials with complex roots, and thus occupy a middle ground between the minimal Winograd algorithms and the Discrete Fourier Transform. If you do this, write a paper. :-)

**Comment by andravin** [comment]
I should also add that larger tile sizes are not always faster in practice. If your application requires a small input size (say batch size 1, and small feature map Height and Width), or the size of your processor's caches is small (as on a typical GPU), a smaller tile might achieve much higher computational efficiency.

In the small data / small cache regime, it is worth examining the possibility that you leave one dimension of the convolution as a direct convolution. This gives you high computational intensity and small tile size. This approach might especially make sense in a hardware accelerator where MACs are cheap but memory extremely limited.

**Comment by lujnan** [comment]
Whether also need nest F(M,5) with F(M,3) for the formal F(M, 5x3) ?

**Comment by andravin** [comment]
I am not sure what you mean by F(M, 5x3).

F(MxN, 5x3) is 2D convolution with a 5x3 filter producing an MxN output tile.
F(M,5) is 1D convolution with a 5-tap filter producing an M element output.
F(N,3) is 1D convolution with a 3-tap filter producing an N element output.

What is F(M, 5x3)?

**Comment by lujnan** [comment]
F(MxM,5x3)

**Comment by andravin** [comment]
Well Winograd's minimal convolution algorithms are 1-D algorithms. Generally you can build a 2-D convolution algorithm by nesting 1-D algorithms.

That is why I say you construct F(MxN, RxS) by nesting F(M,R) with F(N,S). I am not going to give a different answer to that question for particular values of M,N,R, and S.
