### ISSUE TITLE
source code about GPU implementation

### ISSUE THREAD

**Issue by NHZlX** [andravin/wincnn#2]
hi i am reading you paper about "Fast Algorithms for Convolutional Neural Networks". I am interested in it, can you offer the source code about GPU implementation mentioned in the paper. Many thanks!

**Comment by adam-dziedzic** [comment]
Could I also get access to the GPU source code?

**Comment by andravin** [comment]
The kernels are part of the Nervana Neon framework. They are written in NVIDIA's Maxwell/Pascal shader assembly language. You can find them here: https://github.com/NervanaSystems/neon/blob/master/neon/backends/kernels/sass/
