### ISSUE TITLE
Q: Differences in result.

### ISSUE THREAD

**Issue by cbalint13** [andravin/wincnn#21]
May I ask what is the difference between result below and [paper](https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Lavin_Fast_Algorithms_for_CVPR_2016_paper.pdf) ?
```
>>> wincnn.showCookToomConvolution((0,1,-1),2,3)
A = 
⎡1  0 ⎤
⎢     ⎥
⎢1  1 ⎥
⎢     ⎥
⎢1  -1⎥
⎢     ⎥
⎣0  1 ⎦
```
or better:
```
>>> wincnn.showCookToomFilter((0,1,-1), 2, 3)
AT = 
⎡1  1  1   0⎤
⎢           ⎥
⎣0  1  -1  1⎦
```
compared versus paper (pg. 4014 fig. 7):
```
AT =
[1 1 1 0]
[0 1 −1 −1]
```

Q: Notice the minus sign on lower-right element on AT (also on rest of B,G), is this normal ?

My goal is to find this mismatch and to see how to replace exactly these [matrices](https://github.com/ajtulloch/tvm/blob/NCHWc-Winograd-X86/topi/python/topi/nn/winograd_util.py) by a routine instead of constant enumeration, but also for integers given the data type ```out_dtype```.

**Comment by andravin** [comment]
You can generally multiply a row of G or BT by a number and divide the
corresponding column of AT by the same number without affecting the result.
So you might see sign flips that cancel each other out when you read these
algorithm so in different publications.

**Comment by cbalint13** [comment]
Thank you Andrew,
 
 * Reminds me of eigen numerics.
