### ISSUE TITLE
How can calculate F(2x3,3x3)?

### ISSUE THREAD

**Issue by weiqingchen110** [andravin/wincnn#27]

**Comment by weiqingchen110** [comment]
Get the answer.

**Comment by andravin** [comment]
The basic idea is to have one algorithm for F(2,3) and another algorithm For F(3,3) and then  nest them.

Normally, if you want F(2x2, 3x3), you are just nesting an algorithm for F(2,3) with itself. It is the same nesting process when using different convolution algorithms for horizontal and vertical dimensions.

Is that enough detail?
