### ISSUE TITLE
wincnn.showCookToomFilter((0,1,-1), 2, 3) 

### ISSUE THREAD

**Issue by wolf1981** [andravin/wincnn#4]
The result of The result wincnn.showCookToomFilter((0,1,-1), 2, 3)  seems do not match the paper.

**Comment by andravin** [comment]
@wolf1981 they are the same if you multiply the 4th column of AT by -1 and divide the 4th row of BT by -1. Any scaling of this kind can be used to adjust the transforms. You can also scale the rows of G (just scale the corresponding column of AT or row of BT by the reciprocal).
