### ISSUE TITLE
For F(3,3)????

### ISSUE THREAD

**Issue by wuzhijiexia** [andravin/wincnn#5]
For F(3,3), what are the AT, G and BT?

wincnn.showCookToomFilter((0,1,-1), 2, 3), what be the parameter values of the function?

**Comment by andravin** [comment]
Here is F(3,3) using the most obvious choice for interpolation points,
(0,-1,1,2)

In[5]: wincnn.showCookToomFilter((0,-1,1,2),3,3)
AT =
⎡1  1   1  1  0⎤
⎢              ⎥
⎢0  -1  1  2  0⎥
⎢              ⎥
⎣0  1   1  4  1⎦

G =
⎡1/2    0     0  ⎤
⎢                ⎥
⎢-1/6  1/6   -1/6⎥
⎢                ⎥
⎢-1/2  -1/2  -1/2⎥
⎢                ⎥
⎢1/6   1/3   2/3 ⎥
⎢                ⎥
⎣ 0     0     1  ⎦

BT =
⎡2  -1  -2  1   0⎤
⎢                ⎥
⎢0  2   -3  1   0⎥
⎢                ⎥
⎢0  -2  -1  1   0⎥
⎢                ⎥
⎢0  -1  0   1   0⎥
⎢                ⎥
⎣0  2   -1  -2  1⎦

FIR filter: AT*((G*g)(BT*d)) =
⎡d[0]⋅g[0] + d[1]⋅g[1] + d[2]⋅g[2]⎤
⎢                                ⎥
⎢d[1]⋅g[0] + d[2]⋅g[1] + d[3]⋅g[2]⎥
⎢                                ⎥
⎣d[2]⋅g[0] + d[3]⋅g[1] + d[4]⋅g[2]⎦

**Comment by andravin** [comment]
For F(m,r), you must supply m+r-2 unique "interpolation points" as the first argument, so it looks like you just needed one more.

**Comment by wuzhijiexia** [comment]
For interpolation points, what does F(m,n) correspond? How should I compute it?

**Comment by andravin** [comment]
Not sure if you are asking how to select interpolation points, how to use wincnn, or how Winograd transforms are derived.

I already showed how to use wincnn to compute F(3,3), which was the original question.
Here it is again:

wincnn.showCookToomFilter((0,-1,1,2),3,3)

Sorry if I misunderstood the second question. If you would clarify it for me I can perhaps give you a better answer.

**Comment by wuzhijiexia** [comment]
My question is that how I should select interpolation points for F(m,n).

Meanwhile, if possible, can you recommed some informations for me about winograd. I read a lot of information about winograd, such as "Shmuel Winograd-Arithmetic complexity of computations", but I still can not understand it how to compute AT/G/BT.

These make me confused, I hope you can help me very much.

**Comment by andravin** [comment]
For understanding the details of the Winograd algorithm, I found the the book by Blahut to be most helpful: "Fast Algorithms for Signal Processing", 2010: https://www.cambridge.org/core/books/fast-algorithms-for-signal-processing/E35F46175F3558980873443CA8A6A4FD#

The recent ICLR workshop paper by Vincent, et al, "On Improving the Numerical Stability of Winograd Convolutions" does a good job of showing how to compute the transforms for the minimal Winograd algorithms, and gives advice about how to select interpolation points. It also argues that scaling the transforms can help improve the numeric stability: https://openreview.net/forum?id=H1ZaRZVKg&noteId=H1ZaRZVKg

**Comment by wuzhijiexia** [comment]
Thank you for your help.

**Comment by programath** [comment]
@andravin Hi, thank you for your references, which helps me a lot. But I want to know how to use winograd if strides>1? Is there any other algorithm for it?

**Comment by andravin** [comment]
Hi @programath .. I must have answered this question in a different thread. It is possible to use Winograd or any convolution algorithm with strides > 1 by decimating the input and filter to make un-strided convolutions, then adding the results.

For example:
```
xoxoxoxoxox
*2
xox
=
xxxxxx * xx + ooooo * o
```

So a 1D stride 2 convolution can be decomposed into the sum of two un-strided convolutions, each using half of the data and filter elements. You can use a Winograd algorithm on each of the un-strided convolutions.

The same technique can be used with strided 2D convolutions, but then you need a sum of 4 un-strided convolutions.

Any book about fast digital signal processing algorithms will have a chapter on "Decimated Convolution" (ie strided convolution), but they usually only discuss the 1D case.

I probably first became aware of this technique from the following paper by Brosch and Tam, which does use 2D decimation in conjunction with FFT convolution: https://www.researchgate.net/profile/Tom_Brosch/publication/267930193_Efficient_Training_of_Convolutional_Deep_Belief_Networks_in_the_Frequency_Domain_for_Application_to_High-Resolution_2D_and_3D_Images/links/55f05f3d08ae0af8ee1d1904.pdf

**Comment by programath** [comment]
Oh, I have just seen it. Thank you so much!

**Comment by andravin** [comment]
Glad it helped .. I just created the Wincnn FAQ to collect answers to frequently asked questions: https://github.com/andravin/wincnn/blob/master/FAQ.md

**Comment by wyzreborn** [comment]
Hi @andravin , I have understood how to compute 2D stride 2 convolution by means of summing  4 un-strided convolutions. Thanks. 
Is there a possibility that Winograd can be directly used on the input tile and filter instead of decimated input and filter if stride is 2. I have tried, but failed.

**Comment by andravin** [comment]
I think the basic idea behind the decimated convolution decomposition is to show that **a stride-2 convolution is really the sum of two different, unrelated stride-1 convolutions**. Because these stride-1 convolutions have no terms in common, there is no algorithm that makes computing them together less work than computing them separately.
