### ISSUE TITLE
for stride = 2?

### ISSUE THREAD

**Issue by jian-ke** [andravin/wincnn#6]
I don't see the analysis in your paper for the convolution whose stride = 2.
do you analysis the ratio for such situation?

**Comment by andravin** [comment]
The general technique for applying a fast algorithm to strided convolution is to first decompose the strided convolution into a sum of un-strided convolutions. In textbooks this is called "decimated" convolution.

For example, 1D stride 2 convolution (*2 below) of a 3x1 kernel "ABC" and signal "XOXOXOX":

`ABC *2 XOXOXOX = AC * XXXX + B * OOO`

You can speed this up by using a fast algorithm for the 2x1, stride 1 convolution with kernel 'AC'.

It's a bit more complicated for 2D, basically you end up with a sum of 4 un-strided convolutions. It's a fun exercise to draw this and work out the details.

Computation of the arithmetic complexity reduction for 3x3 stride2 is left as an exercise for the reader. ;-) You will need fast algorithms for 2x2 and 2x1/1x2 filters.

In any case, the arithmetic complexity reduction of fast 3x3 stride2 convolutions might not make the implementation effort worthwhile, considering these layers typically comprise a small fraction of the total arithmetic OPs of the network.

**Comment by jian-ke** [comment]
Thank you for pointing the way！
