### ISSUE TITLE
What are the polynomial points for F(8,3)???

### ISSUE THREAD

**Issue by wuzhijiexia** [andravin/wincnn#8]
I have read the article "ON IMPROVING THE NUMERICAL STABILITY OF WINOGRAD CONVOLUTIONS", but I still don't know it how to choose the polynomial points.
If possible, can you tell me to the result for the polynomial points of F(8,3)?

**Comment by andravin** [comment]
Here are some possibilities for F(8,3):

` wincnn.showCookToomFilter((0,1,-1,2,-2,Rational(1,2),-Rational(1,2), 3, -3), 8, 3)`

`wincnn.showCookToomFilter((0,1,-1,2,-2,Rational(1,2),-Rational(1,2), 4, -4), 8, 3)`

`wincnn.showCookToomFilter((0,1,-1,2,-2,Rational(1,2),-Rational(1,2), Rational(3,2), -Rational(3,2)), 8, 3)`

It would be an additional step to apply scalings to these transforms, as suggested in the "Improving Stability of Winograd" paper.

**Comment by wuzhijiexia** [comment]
Thank you very much!

**Comment by andravin** [comment]
You are welcome! Keep in mind that the numeric accuracy of these large tile transforms will be less than the F(4,3) or F(2,3). You need to test to ensure they are accurate enough for your application.

**Comment by andravin** [comment]
By the way, in the above example ,`Rational` is in the `sympy` module. Docs are here: http://docs.sympy.org/0.7.1/modules/core.html#rational
