### ISSUE TITLE
F(3,3) vs F(2,3) accuracy

### ISSUE THREAD

**Issue by chasingegg** [andravin/wincnn#9]
hello, 
Recently I want to change F(2,3) algorithm to F(3,3) based on the same input image, but I got errors nearly 1e-3 , is that a normal situation?

**Comment by andravin** [comment]
I have not tested F(3,3) as much as F(2,3) or F(4,3), but the accuracy should be around the same as direct convolution. You should see F(2,3) is slightly more accurate than direct convolution.
